#
# Build
#

build { core init drivers/timer test/affinity_test_parent test/affinity_test_counter_child test/affinity_test_validator_child }

create_boot_directory

#
# Generate config
#

install_config {
<config>
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
	</parent-provides>
	<affinity-space width="4" />	
#	<affinity xpos="0" width="1" />	
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>
	<start name="affinity_test_parent">
		<resource name="RAM" quantum="1G"/>
		<affinity xpos="1" width="3"/>
	</start>
</config>
}

#
# Boot image
#

build_boot_image { core init timer affinity_test_parent child_counter child_validator }

append qemu_args " -nographic -smp 4 "

run_genode_until forever
 