#
# Build
#

build { core init rtcr test/rtcr_session_driver }

create_boot_directory

#
# Generate config
#

install_config {
<config>
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="rtcr">
		<resource name="RAM" quantum="10M"/>
		<provides><service name="Rtcr"/></provides>
	</start>
	<start name="rtcr_driver">
		<resource name="RAM" quantum="1M"/>
	</start>
</config>}

#
# Boot image
#

build_boot_image { core init rtcr rtcr_driver }

append qemu_args " -nographic "

run_genode_until "Rtcr-driver ended.*\n" 15
