build { core init test/cr_driver }

create_boot_directory

install_config {
<config>
  <parent-provides>
    <service name="LOG"/>
    <service name="CR"/>
  </parent-provides>
  <default-route>
    <any-service> <parent/> <any-child/> </any-service>
  </default-route>
  <start name="test-cr_driver">
    <resource name="RAM" quantum="1M"/>
  </start>
</config>}

build_boot_image { core init test-cr_driver }

append qemu_args " -nographic "

run_genode_until "hello core test completed.*\n" 10
